<a href="https://colab.research.google.com/github/Ghan539/Python4DataScientist/blob/main/myntra_data_cleaning_project/myntra_sales_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [103]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [104]:
mn=pd.read_csv('/content/Myntra products .csv')

In [105]:
myntra=mn.copy()

In [106]:
myntra.head(2)

,url,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,...,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers
0,https://www.myntra.com/jackets/rare-rabbit/rar...,20319780,RARE RABBIT,Men Maroon Striped Crop Denim Jacket with Patc...,4.2,20,"""₹4,299.00""",25.0,"""₹3,224.00""",INR,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",RADHAMANI TEXTILES PVT LTD,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C...",NaN,"314 315 316 317 318 319, GR FLOOR, JIGANI INDU...",[{}],"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI..."
1,https://www.myntra.com/jumpsuit/showoff/showof...,20286668,SHOWOFF,White & Red Shoulder Strap Printed Basic Jumpsuit,4.0,6,"""₹5,780.00""",69.0,"""₹1,791.00""",INR,...,"[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,SHOWOFF,"[{""size"":""M"",""value"":""36.0in"",""value_name"":""To...",NaN,"1371,SURVEY NO.62,6TH CROSS,N.S.PALLYA,BTM 2ND...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI..."

In [107]:
# drop columns
# images
# product_specifications
# videos
# seller_information
# variations
# best_offer
# more_offers

col=['images','product_specifications','videos','seller_information','variations','best_offer','more_offers']

In [108]:
# drop unwanted columns


myntra.drop(columns=col,inplace=True)

In [109]:
# basic information of myntra data

myntra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   url                  1000 non-null   object
 1   product_id           1000 non-null   int64
 2   title                1000 non-null   object
 3   product_description  1000 non-null   object
 4   rating               1000 non-null   float64
 5   ratings_count        1000 non-null   int64
 6   initial_price        1000 non-null   object
 7   discount             912 non-null    float64
 8   final_price          1000 non-null   object
 9   currency             1000 non-null   object
 10  delivery_options     1000 non-null   object
 11  product_details      1000 non-null   object
 12  breadcrumbs          1000 non-null   object
 13  amount_of_stars      1000 non-null   object
 14  what_customers_said  291 non-null    object
 15  seller_name          916 non-null    object
 16  sizes                1000 non-null   object
dtypes: float64(2), int64(2), object(13)
memory usage: 132.9+ KB

In [110]:
# total rows and columns in the data set

myntra.shape

(1000, 17)

In [111]:
# total null values in the dataset

myntra[myntra['discount'].isnull()][['initial_price','final_price']]

    initial_price  final_price
10      "₹699.00"    "₹699.00"
13    "₹1,999.00"  "₹1,999.00"
32      "₹545.00"    "₹545.00"
41      "₹999.00"    "₹999.00"
49    "₹1,799.00"  "₹1,799.00"
..            ...          ...
934   "₹1,495.00"  "₹1,495.00"
940   "₹1,299.00"  "₹1,299.00"
953   "₹1,999.00"  "₹1,999.00"
979   "₹3,199.00"  "₹3,199.00"
998     "₹629.00"    "₹629.00"

[88 rows x 2 columns]

In [112]:
myntra['initial_price'].isnull().sum()

np.int64(0)

In [113]:
myntra['final_price'].isnull().sum()

np.int64(0)

In [114]:
(myntra['initial_price'] == myntra['final_price']).sum()

np.int64(161)

In [115]:
# those 73 values
# initial == final then the discount is 0
myntra[(myntra['initial_price'] == myntra['final_price']) & (myntra['discount'].notna())][['initial_price','final_price','discount']]

    initial_price  final_price  discount
2     "₹1,195.00"  "₹1,195.00"      51.0
3     "₹5,700.00"  "₹5,700.00"      69.0
4     "₹1,240.00"  "₹1,240.00"      70.0
5       "₹999.00"    "₹999.00"      60.0
26    "₹1,999.00"  "₹1,999.00"      75.0
..            ...          ...       ...
916   "₹1,890.00"  "₹1,890.00"      37.0
936     "₹999.00"    "₹999.00"      60.0
937   "₹1,999.00"  "₹1,999.00"      65.0
948     "₹799.00"    "₹799.00"      30.0
961   "₹5,949.00"  "₹5,949.00"      82.0

[80 rows x 3 columns]

In [116]:
# min discount

myntra['discount'].min()

1.0

In [117]:
# product id of min discount== 2 products

myntra[myntra['discount'] == 1.0]

,url,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,delivery_options,product_details,breadcrumbs,amount_of_stars,what_customers_said,seller_name,sizes
293,https://www.myntra.com/table-placemats/jasmey-...,17639790,JASMEY HOMES,Set Of 4 White & Brown Textured Jute Dining Ta...,4.5,6,"""₹899.00""",1.0,"""₹890.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: 4 table placemats...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,House of Creations,"[{""size"":""M""}]"
524,https://www.myntra.com/table-placemats/jasmey-...,17639816,JASMEY HOMES,Set of 4 Yellow & Beige Braided Jute Table Pla...,4.2,5,"""₹899.00""",1.0,"""₹890.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: 4 Table placemats...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,House of Creations,"[{""size"":""M""}]"

In [118]:
# max discount

myntra['discount'].max()

85.0

In [119]:
# product id of max discount== products
myntra[myntra['discount'] == 85.0]

,url,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,delivery_options,product_details,breadcrumbs,amount_of_stars,what_customers_said,seller_name,sizes
110,https://www.myntra.com/watches/rizzly/rizzly-g...,14972496,Rizzly,Girls White Brass Printed Dial & White Leather...,2.8,11,"""₹1,999.00""",85.0,"""₹299.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watch D...","[{""name"":""Accessories"",""url"":""https://www.mynt...","{""1_star"":3,""2_stars"":2,""3_stars"":3,""4_stars"":...",NaN,Jay Khodal Creation,"[{""size"":""Onesize""}]"
346,https://www.myntra.com/sarees/vairagee/vairage...,17483410,VAIRAGEE,Navy Blue Embroidered Pure Georgette Saree,3.9,7,"""₹9,500.00""",85.0,"""₹1,425.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Design Details Navy blue s...","[{""name"":""Clothing"",""url"":""https://www.myntra....","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fabric Qual...",Vivera International,"[{""size"":""Onesize""}]"
627,https://www.myntra.com/watches/rizzly/rizzly-g...,14972528,Rizzly,Girls Black Brass Dial & Leather Straps Analog...,3.4,33,"""₹1,999.00""",85.0,"""₹299.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watchDis...","[{""name"":""Accessories"",""url"":""https://www.mynt...","{""1_star"":6,""2_stars"":5,""3_stars"":5,""4_stars"":...",NaN,Jay Khodal Creation,"[{""size"":""Onesize""}]"
753,https://www.myntra.com/watches/rizzly/rizzly-w...,14972500,Rizzly,Women Blue Brass Embellished Dial & Blue Leath...,0.0,0,"""₹1,999.00""",85.0,"""₹299.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: 2 watchDisplay:...","[{""name"":""Accessories"",""url"":""https://www.mynt...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Jay Khodal Creation,"[{""size"":""Onesize""}]"
955,https://www.myntra.com/watches/swadesi-stuff/s...,14905170,SWADESI STUFF,Unisex Multicoloured Dial & Black Straps Digit...,3.4,7,"""₹1,995.00""",85.0,"""₹299.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watchDis...","[{""name"":""Accessories"",""url"":""https://www.mynt...","{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,SWADESI STUFF,"[{""size"":""Onesize""}]"
957,https://www.myntra.com/watches/swadesi-stuff/s...,14905176,SWADESI STUFF,Unisex Red Dial & Black Straps Digital Automat...,3.8,24,"""₹1,995.00""",85.0,"""₹299.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watchDis...","[{""name"":""Accessories"",""url"":""https://www.mynt...","{""1_star"":4,""2_stars"":1,""3_stars"":4,""4_stars"":...",NaN,SWADESI STUFF,"[{""size"":""Onesize""}]"
995,https://www.myntra.com/watches/rizzly/rizzly-g...,14972510,Rizzly,Girls Peach Brass Printed Dial & Orange Leathe...,3.7,74,"""₹1,999.00""",85.0,"""₹299.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watchDis...","[{""name"":""Accessories"",""url"":""https://www.mynt...","{""1_star"":14,""2_stars"":5,""3_stars"":8,""4_stars""...",NaN,Jay Khodal Creation,"[{""size"":""Onesize""}]"

In [120]:
myntra['discount'].dtypes

dtype('float64')

In [121]:
((myntra['initial_price'] == myntra['final_price']) & (myntra['discount'].notna())).sum()

np.int64(80)

In [122]:
myntra[['initial_price','final_price']].isna().sum()

initial_price    0
final_price      0
dtype: int64

In [123]:
myntra[myntra['discount'].isnull()][['initial_price','final_price']].shape

(88, 2)

In [124]:
myntra['discount'].notna().sum()

np.int64(912)

In [125]:
myntra['discount'].value_counts(dropna=False)

discount
NaN     88
50.0    64
60.0    63
65.0    48
20.0    48
        ..
17.0     1
2.0      1
16.0     1
12.0     1
9.0      1
Name: count, Length: 76, dtype: int64

In [126]:
myntra[myntra['discount'].isnull()]

,url,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,delivery_options,product_details,breadcrumbs,amount_of_stars,what_customers_said,seller_name,sizes
10,https://www.myntra.com/kurtas/indus-route-by-p...,15465822,indus route by Pantaloons,Men Rust Thread Work Pathani Kurta,3.6,14,"""₹699.00""",NaN,"""₹699.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Colour: rust Solid woven d...","[{""name"":""Clothing"",""url"":""https://www.myntra....","{""1_star"":3,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,Westbury Holdings Pvt Ltd_Pantaloons,"[{""size"":""S"",""value"":""42.0in"",""value_name"":""Ch..."
13,https://www.myntra.com/watches/sonata/sonata-w...,15615024,Sonata,Women Rose Gold-Toned Brass Dial & Bracelet St...,4.5,24,"""₹1,999.00""",NaN,"""₹1,999.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watch D...","[{""name"":""Accessories"",""url"":""https://www.mynt...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Truecom Retail,"[{""size"":""Onesize""}]"
32,https://www.myntra.com/shampoo-and-conditioner...,17646738,TRUe FRoG,Pea Sprout & Bhringraj Extract Anti Hair Fall ...,4.2,18,"""₹545.00""",NaN,"""₹545.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pea Sprout & Bhringraj Extract...","[{""name"":""Personal Care"",""url"":""https://www.my...","{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,EarthyBlend Private Limited,"[{""size"":""240-260 ML""}]"
41,https://www.myntra.com/tshirts/lastinch/lastin...,17732148,LastInch,Women Beige V-Neck Casual Cotton T-shirt,4.3,6,"""₹999.00""",NaN,"""₹999.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Beige Tshirt for women Sol...","[{""name"":""Clothing"",""url"":""https://www.myntra....","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",LAST INCH APPAREL PRIVATE LIMITED,"[{""size"":""M"",""value"":""42.0in"",""value_name"":""Bu..."
49,https://www.myntra.com/wallets/yessbenza/yessb...,20840564,YESSBENZA,Women Peach-Coloured & Gold-Toned Two Fold Wal...,3.9,9,"""₹1,799.00""",NaN,"""₹1,799.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Peach-coloured solid self desi...","[{""name"":""Accessories"",""url"":""https://www.mynt...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Raaq Creation,"[{""size"":""Onesize""}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
934,https://www.myntra.com/shirts/20dresses/20dres...,17582592,20Dresses,Women Maroon Party Crop Shirt,4.1,14,"""₹1,495.00""",NaN,"""₹1,495.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Maroon solid opaque Party shir...","[{""name"":""Clothing"",""url"":""https://www.myntra....","{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,OUTLETWISE RETAIL PVT LTD,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T..."
940,https://www.myntra.com/track-pants/marks--spen...,21177968,Marks & Spencer,Girls Bunny Printed Cotton Joggers,4.2,6,"""₹1,299.00""",NaN,"""₹1,299.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Bunny printed joggers has slip...","[{""name"":""Clothing"",""url"":""https://www.myntra....","{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,MARKS AND SPENCER RELIANCE INDIA PRIVATE LIMITED,"[{""size"":""2-3Y"",""value"":""22.0in"",""value_name"":..."
953,https://www.myntra.com/wallets/yessbenza/yessb...,20379622,YESSBENZA,Women Black Bow Detail Two Fold Wallet,4.1,7,"""₹1,999.00""",NaN,"""₹1,999.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Black brand logo self design b...","[{""name"":""Accessories"",""url"":""https://www.mynt...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Raaq Creation,"[{""size"":""Onesize""}]"
979,https://www.myntra.com/jeans/levis/levis-men-b...,18074908,Levis,Men Blue 512 Slim Fit Mid-Rise Light Fade Stre...,4.1,878,"""₹3,199.00""",NaN,"""₹3,199.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Medium shade, light fade bl...","[{""name"":""Clothing"",""url"":""https://www.myntra....","{""1_star"":101,""2_stars"":22,""3_stars"":67,""4_sta...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Vision Star,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T..."
998,https://www.myntra.com/thermal-bottoms/jockey/...,15002364,Jockey,Women Off-White Thermal Leggings,4.5,225,"""₹629.00""",NaN,"""₹629.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Off -white leggings with Jocke...","[{""name"":""Clothing"",""url"":""https://www.myntra....","{""1_star"":9,""2_stars"":2,""3_stars"":16,""4_stars""...",NaN,Page Industries Ltd,"[{""size"":""S"",""value"":""30.0in"",""value_name"":""To..."

In [127]:
((myntra['initial_price'] == myntra['final_price']) & (myntra['discount'].isnull())).sum()

np.int64(81)

In [128]:
# dtype of initial and final price

myntra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   url                  1000 non-null   object
 1   product_id           1000 non-null   int64
 2   title                1000 non-null   object
 3   product_description  1000 non-null   object
 4   rating               1000 non-null   float64
 5   ratings_count        1000 non-null   int64
 6   initial_price        1000 non-null   object
 7   discount             912 non-null    float64
 8   final_price          1000 non-null   object
 9   currency             1000 non-null   object
 10  delivery_options     1000 non-null   object
 11  product_details      1000 non-null   object
 12  breadcrumbs          1000 non-null   object
 13  amount_of_stars      1000 non-null   object
 14  what_customers_said  291 non-null    object
 15  seller_name          916 non-null    object
 16  sizes                1000 non-null   object
dtypes: float64(2), int64(2), object(13)
memory usage: 132.9+ KB

part 2

In [131]:
myntra.head(1)

,url,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,delivery_options,product_details,breadcrumbs,amount_of_stars,what_customers_said,seller_name,sizes
0,https://www.myntra.com/jackets/rare-rabbit/rar...,20319780,RARE RABBIT,Men Maroon Striped Crop Denim Jacket with Patc...,4.2,20,"""₹4,299.00""",25.0,"""₹3,224.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Maroon solid striped denim jac...","[{""name"":""Clothing"",""url"":""https://www.myntra....","{""1_star"":0,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",RADHAMANI TEXTILES PVT LTD,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C..."

In [132]:
# remove the ₹ and " " from the initial and final_price column
myntra['initial_price'] = myntra['initial_price'].str.replace('₹','',regex=False)
myntra['final_price'] = myntra['final_price'].str.replace('₹','',regex=False)

In [133]:
# remove  " "  and "," from the initial and final_price column

myntra['initial_price'] = myntra['initial_price'].str.replace('"','',regex=False).str.replace(',','',regex=False)
myntra['final_price'] = myntra['final_price'].str.replace('"','',regex=False).str.replace(',','',regex=False)

In [134]:
myntra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   url                  1000 non-null   object
 1   product_id           1000 non-null   int64
 2   title                1000 non-null   object
 3   product_description  1000 non-null   object
 4   rating               1000 non-null   float64
 5   ratings_count        1000 non-null   int64
 6   initial_price        1000 non-null   object
 7   discount             912 non-null    float64
 8   final_price          1000 non-null   object
 9   currency             1000 non-null   object
 10  delivery_options     1000 non-null   object
 11  product_details      1000 non-null   object
 12  breadcrumbs          1000 non-null   object
 13  amount_of_stars      1000 non-null   object
 14  what_customers_said  291 non-null    object
 15  seller_name          916 non-null    object
 16  sizes                1000 non-null   object
dtypes: float64(2), int64(2), object(13)
memory usage: 132.9+ KB

In [136]:
myntra.head(1)

,url,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,delivery_options,product_details,breadcrumbs,amount_of_stars,what_customers_said,seller_name,sizes
0,https://www.myntra.com/jackets/rare-rabbit/rar...,20319780,RARE RABBIT,Men Maroon Striped Crop Denim Jacket with Patc...,4.2,20,4299.00,25.0,3224.00,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Maroon solid striped denim jac...","[{""name"":""Clothing"",""url"":""https://www.myntra....","{""1_star"":0,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",RADHAMANI TEXTILES PVT LTD,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C..."

In [139]:
# astype change of initial and final price
myntra['initial_price'] = myntra['initial_price'].astype(float)
myntra['final_price'] = myntra['final_price'].astype(float)
myntra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   url                  1000 non-null   object
 1   product_id           1000 non-null   int64
 2   title                1000 non-null   object
 3   product_description  1000 non-null   object
 4   rating               1000 non-null   float64
 5   ratings_count        1000 non-null   int64
 6   initial_price        1000 non-null   float64
 7   discount             912 non-null    float64
 8   final_price          1000 non-null   float64
 9   currency             1000 non-null   object
 10  delivery_options     1000 non-null   object
 11  product_details      1000 non-null   object
 12  breadcrumbs          1000 non-null   object
 13  amount_of_stars      1000 non-null   object
 14  what_customers_said  291 non-null    object
 15  seller_name          916 non-null    object
 16  sizes                1000 non-null   object
dtypes: float64(4), int64(2), object(11)
memory usage: 132.9+ KB

In [140]:
# create new discount column
myntra['final_discount'] = myntra['initial_price'] - myntra['final_price']

In [141]:
myntra.head(1)

,url,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,delivery_options,product_details,breadcrumbs,amount_of_stars,what_customers_said,seller_name,sizes,final_discount
0,https://www.myntra.com/jackets/rare-rabbit/rar...,20319780,RARE RABBIT,Men Maroon Striped Crop Denim Jacket with Patc...,4.2,20,4299.0,25.0,3224.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Maroon solid striped denim jac...","[{""name"":""Clothing"",""url"":""https://www.myntra....","{""1_star"":0,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",RADHAMANI TEXTILES PVT LTD,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C...",1075.0

In [144]:
# change name of discount column to  discount_per
myntra.rename(columns={'discount': 'discount_per'},inplace=True)

In [150]:
# change column position
col=myntra.pop('final_discount')
myntra.insert(7,'discount',col)

In [152]:
# change column position

col=myntra.pop('discount_per')
myntra.insert(9,'discount_per',col)

In [155]:
col=myntra.pop('final_price')
myntra.insert(7,'final_price',col)

In [156]:
myntra.columns

Index(['url', 'product_id', 'title', 'product_description', 'rating',
       'ratings_count', 'initial_price', 'final_price', 'discount',
       'discount_per', 'currency', 'delivery_options', 'product_details',
       'breadcrumbs', 'amount_of_stars', 'what_customers_said', 'seller_name',
       'sizes'],
      dtype='object')

In [158]:
# drop columns
myntra.drop(columns=['url','product_details','breadcrumbs'],inplace=True)

In [159]:
myntra['discount_per2'] = ((myntra['initial_price'] - myntra['final_price'])/myntra['initial_price'])*100

In [162]:
# change column position
col=myntra.pop('discount_per2')
myntra.insert(9,'discount_per2',col)

In [166]:
# 25.005815 → 25.0
# round the values

myntra['discount_per2'] = myntra['discount_per2'].round(1)

In [170]:
myntra[myntra['discount_per2'] == 0.0].shape

(161, 16)

In [173]:
# no of discount_per col with zero discount but value assigned is NAN
myntra.loc[(myntra['initial_price'] == myntra['final_price']) & (myntra['discount_per'].isnull()),'discount_per'] = 0.0

In [179]:
#  nan values but acutal values is not 0 its diff

myntra['discount_per'].isnull().sum()

np.int64(7)

In [181]:
myntra.loc[myntra['discount_per'].isnull(),'discount_per'] = (((myntra['initial_price'] - myntra['final_price'])/myntra['initial_price'])*100).round(1)

In [185]:
# no of matching rows in column['discount_per']  and column['discount_per2']


myntra[myntra['discount_per'] == myntra['discount_per2']].shape[0]

631

In [186]:

myntra[myntra['discount_per'] != myntra['discount_per2']].shape[0]

369

In [189]:
myntra[myntra['discount_per'] != myntra['discount_per2']][['initial_price','final_price','discount_per','discount_per2']]

     initial_price  final_price  discount_per  discount_per2
2           1195.0       1195.0          51.0            0.0
3           5700.0       5700.0          69.0            0.0
4           1240.0       1240.0          70.0            0.0
5            999.0        999.0          60.0            0.0
7            699.0        454.0          35.0           35.1
..             ...          ...           ...            ...
980         1349.0        337.0          59.0           75.0
981         2899.0       1652.0          20.0           43.0
986          549.0        219.0          60.0           60.1
988         1079.0        449.0          58.0           58.4
999          999.0        349.0          65.0           65.1

[369 rows x 4 columns]

In [193]:
# no of rows where initail and final values same but discount is not zero

myntra[(myntra['initial_price'] == myntra['final_price']) & (myntra['discount_per'] !=0)].shape

(80, 16)

In [195]:
myntra.loc[(myntra['initial_price'] == myntra['final_price']) & (myntra['discount_per'] !=0),'discount_per'] = 0.0

In [201]:

# zero discount in colum['discount_per']

myntra[myntra['discount_per'] == 0].shape

(161, 16)

In [202]:
# zero discount in colum['discount_per2']
myntra[myntra['discount_per2'] == 0].shape

(161, 16)

In [206]:
# see the biggest discrepancies:

# is discount_per == discount_per2
myntra[myntra['discount_per'] != myntra['discount_per2']][['initial_price','final_price','discount_per','discount_per2']]

     initial_price  final_price  discount_per  discount_per2
7            699.0        454.0          35.0           35.1
16          1349.0        512.0          55.0           62.0
18          1999.0        559.0          67.0           72.0
19          1499.0        479.0          60.0           68.0
21          1149.0        379.0          60.0           67.0
..             ...          ...           ...            ...
980         1349.0        337.0          59.0           75.0
981         2899.0       1652.0          20.0           43.0
986          549.0        219.0          60.0           60.1
988         1079.0        449.0          58.0           58.4
999          999.0        349.0          65.0           65.1

[289 rows x 4 columns]

part3

In [208]:
myntra.set_index('product_id',inplace=True)

In [209]:
myntra.head(2)

,title,product_description,rating,ratings_count,initial_price,final_price,discount,discount_per,discount_per2,currency,delivery_options,amount_of_stars,what_customers_said,seller_name,sizes
product_id,,,,,,,,,,,,,,,
20319780,RARE RABBIT,Men Maroon Striped Crop Denim Jacket with Patc...,4.2,20,4299.0,3224.0,1075.0,25.0,25.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":0,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",RADHAMANI TEXTILES PVT LTD,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C..."
20286668,SHOWOFF,White & Red Shoulder Strap Printed Basic Jumpsuit,4.0,6,5780.0,1791.0,3989.0,69.0,69.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,SHOWOFF,"[{""size"":""M"",""value"":""36.0in"",""value_name"":""To..."

In [214]:
# drop discount_per2 as it has wrong calculated discounts

# myntra.drop(columns='discount_per',inplace=True)

In [213]:
myntra.head(2)

,title,product_description,rating,ratings_count,initial_price,final_price,discount,discount_per2,currency,delivery_options,amount_of_stars,what_customers_said,seller_name,sizes
product_id,,,,,,,,,,,,,,
20319780,RARE RABBIT,Men Maroon Striped Crop Denim Jacket with Patc...,4.2,20,4299.0,3224.0,1075.0,25.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":0,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",RADHAMANI TEXTILES PVT LTD,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C..."
20286668,SHOWOFF,White & Red Shoulder Strap Printed Basic Jumpsuit,4.0,6,5780.0,1791.0,3989.0,69.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,SHOWOFF,"[{""size"":""M"",""value"":""36.0in"",""value_name"":""To..."

clean size column

In [219]:
type(myntra['sizes'].iloc[0])

str

In [220]:
myntra['sizes'].iloc[0]

'[{"size":"XS","value":"42.5in","value_name":"Chest"},{"size":"XS","value":"29.58in","value_name":"Front Length"},{"size":"XS","value":"17.5in","value_name":"Across Shoulder"},{"size":"S","value":"45.0in","value_name":"Chest"},{"size":"S","value":"30.42in","value_name":"Front Length"},{"size":"S","value":"18.33in","value_name":"Across Shoulder"},{"size":"M","value":"47.5in","value_name":"Chest"},{"size":"M","value":"31.25in","value_name":"Front Length"},{"size":"M","value":"19.17in","value_name":"Across Shoulder"},{"size":"L","value":"50.0in","value_name":"Chest"},{"size":"L","value":"31.67in","value_name":"Front Length"},{"size":"L","value":"20.0in","value_name":"Across Shoulder"},{"size":"XL","value":"52.5in","value_name":"Chest"},{"size":"XL","value":"32.5in","value_name":"Front Length"},{"size":"XL","value":"20.83in","value_name":"Across Shoulder"},{"size":"XXL","value":"55.0in","value_name":"Chest"},{"size":"XXL","value":"32.92in","value_name":"Front Length"},{"size":"XXL","value":"21.67in","value_name":"Across Shoulder"},{"size":"3XL","value":"57.5in","value_name":"Chest"},{"size":"3XL","value":"33.33in","value_name":"Front Length"},{"size":"3XL","value":"22.5in","value_name":"Across Shoulder"}]'

In [ ]:
myntra['size'] = myntra['sizes'].str.extract()

In [223]:
myntra['delivery_options']

product_id
20319780    ["100% Original Products","Pay on delivery mig...
20286668    ["100% Original Products","Pay on delivery mig...
13842592    ["100% Original Products","Pay on delivery mig...
14088708    ["100% Original Products","Pay on delivery mig...
11515678    ["100% Original Products","Pay on delivery mig...
                                  ...
14972510    ["100% Original Products","Pay on delivery mig...
15000460    ["100% Original Products","Pay on delivery mig...
15017874    ["100% Original Products","Pay on delivery mig...
15002364    ["100% Original Products","Pay on delivery mig...
21841102    ["100% Original Products","Pay on delivery mig...
Name: delivery_options, Length: 1000, dtype: object

In [224]:
myntra.head(2)

,title,product_description,rating,ratings_count,initial_price,final_price,discount,discount_per2,currency,delivery_options,amount_of_stars,what_customers_said,seller_name,sizes
product_id,,,,,,,,,,,,,,
20319780,RARE RABBIT,Men Maroon Striped Crop Denim Jacket with Patc...,4.2,20,4299.0,3224.0,1075.0,25.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":0,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",RADHAMANI TEXTILES PVT LTD,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C..."
20286668,SHOWOFF,White & Red Shoulder Strap Printed Basic Jumpsuit,4.0,6,5780.0,1791.0,3989.0,69.0,INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,SHOWOFF,"[{""size"":""M"",""value"":""36.0in"",""value_name"":""To..."

part3

In [226]:
myntra2 = myntra[['title','rating','ratings_count','initial_price','final_price','discount','discount_per2','currency','seller_name']]

In [229]:
myntra2.head()

,title,rating,ratings_count,initial_price,final_price,discount,discount_per2,currency,seller_name
product_id,,,,,,,,,
20319780,RARE RABBIT,4.2,20,4299.0,3224.0,1075.0,25.0,INR,RADHAMANI TEXTILES PVT LTD
20286668,SHOWOFF,4.0,6,5780.0,1791.0,3989.0,69.0,INR,SHOWOFF
13842592,VASTRANAND,4.0,67,1195.0,1195.0,0.0,0.0,INR,NaN
14088708,VASTRANAND,4.5,43,5700.0,5700.0,0.0,0.0,INR,NaN
11515678,Soie,4.4,16,1240.0,1240.0,0.0,0.0,INR,NaN

In [268]:
# filling nan values in sellers_name column
myntra['seller_name'] = myntra2['seller_name'].fillna('not avail')

In [254]:
# total listed selling

myntra2['final_price'].sum()

np.float64(1260273.0)

In [262]:
#  frquency of sellers

myntra2['seller_name'].value_counts()

seller_name
Supercom Net                       65
Flashstar Commerce                 30
Amitto                             29
Vision Star                        26
S & S Marketing                    24
                                   ..
DIVINE INTERNATIONAL TRADING CO     1
White World                         1
Kotty Lifestyle Pvt Ltd             1
RADHAMANI TEXTILES PVT LTD          1
ETAIL MARKETING PVT LTD             1
Name: count, Length: 281, dtype: int64

In [276]:
myntra2['seller_name'].isna().sum()

np.int64(0)

In [277]:
myntra2['seller_name'].head(15)

product_id
20319780                  RADHAMANI TEXTILES PVT LTD
20286668                                     SHOWOFF
13842592                               Not Available
14088708                               Not Available
11515678                               Not Available
13913488                               Not Available
22424746                     Kotty Lifestyle Pvt Ltd
21573924    Bioworld Merchandising (India) Pvt. Ltd.
12739096                          KIAH FASHION HOUSE
15475818                              Miaz lifestyle
15465822        Westbury Holdings Pvt Ltd_Pantaloons
15488894                               Indiflashmart
15523390                                      Amitto
15615024                              Truecom Retail
18207528                                 Vision Star
Name: seller_name, dtype: object

In [278]:
myntra2.to_csv('myntra_cleaned_datafinal.csv')