<a href="https://colab.research.google.com/github/Ghan539/Python4DataScientist/blob/main/pandas/session22_pandas_strings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# What are vectorized operations
a=np.array([1,2,3,4])
a*4

array([ 4,  8, 12, 16])

In [ ]:
# problem in vectorized opertions in vanilla python

s=['cat','mat','rat','mice','Cile']
[i.lower().startswith('c') for i in s]

[True, False, False, False, True]

In [ ]:
#  How pandas solves this issue?

s=pd.Series(['cat','mat','rat','mice','Cile'])
s

0     cat
1     mat
2     rat
3    mice
4    Cile
dtype: object

In [ ]:
# str is an accessor

s.str.startswith('c')

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
# import titanic

t=pd.read_csv('/content/titanic.csv')
t.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
tit=t['Name']
tit

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
tit.str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [ ]:
tit.str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: object

In [ ]:
tit.str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [ ]:
tit.str.title()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# len

tit.str.len().max()

82

In [ ]:
tit[tit.str.len()==82]

307    Penasco y Castellana, Mrs. Victor de Satode (M...
Name: Name, dtype: object

In [ ]:
# strip--removes unwanted spacecs

tit.str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# split

tit.str.split()

0                           [Braund,, Mr., Owen, Harris]
1      [Cumings,, Mrs., John, Bradley, (Florence, Bri...
2                             [Heikkinen,, Miss., Laina]
3      [Futrelle,, Mrs., Jacques, Heath, (Lily, May, ...
4                          [Allen,, Mr., William, Henry]
                             ...
886                            [Montvila,, Rev., Juozas]
887                    [Graham,, Miss., Margaret, Edith]
888       [Johnston,, Miss., Catherine, Helen, "Carrie"]
889                           [Behr,, Mr., Karl, Howell]
890                              [Dooley,, Mr., Patrick]
Name: Name, Length: 891, dtype: object

In [ ]:
tit.str.split(',').str.get(0)

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Name, Length: 891, dtype: object

In [ ]:
t['lastname']=tit.str.split(',').str.get(0)

0                                  [Braund,  Mr. Owen Harris]
1           [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                                   [Heikkinen,  Miss. Laina]
3             [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                                 [Allen,  Mr. William Henry]
                                  ...
887                           [Graham,  Miss. Margaret Edith]
888               [Johnston,  Miss. Catherine Helen "Carrie"]
889                                  [Behr,  Mr. Karl Howell]
890                                    [Dooley,  Mr. Patrick]
lastname                                                  NaN
Name: Name, Length: 892, dtype: object

In [ ]:
t[['title','first_name']]=tit.str.split(',').str.get(1).str.strip().str.split(' ',n=1,expand=True)
t.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,lastname,title,first_name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry

In [ ]:
t['title'].value_counts()

title
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Col.           2
Mlle.          2
Major.         2
Ms.            1
Mme.           1
Don.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [ ]:
# replace
# miss====ms===mlle



t['title'] = t['title'].str.replace('Ms.','Miss.')

t['title'] = t['title'].str.replace('Mlle.','Miss.')

t['title'].value_counts()

title
Mr.          517
Miss.        185
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Col.           2
Don.           1
Lady.          1
Mme.           1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [ ]:
t['title'].value_counts()

title
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Col.           2
Mlle.          2
Major.         2
Ms.            1
Mme.           1
Don.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [ ]:
# filtering
# startswith/endswith
t[t['first_name'].str.startswith('B')]['first_name']

47                                 Bridget
82                           Brigdet Delia
84                                  Bertha
93                           Bertram Frank
109                                 Bertha
231                            Bengt Edvin
301                                Bernard
314                               Benjamin
389                                 Bertha
429                  Berk (Berk Trembisky)
440       Benjamin (Esther Ada Bloomfield)
444                                  Bernt
452                     Benjamin Laventall
502                           Bridget Mary
537                                 Bertha
687                                 Branko
710    Berthe Antonine ("Mrs de Villiers")
780                                Banoura
788                           Bertram Vere
789                               Benjamin
Name: first_name, dtype: object

In [ ]:
t[t['first_name'].str.endswith('B')]['first_name']

96    George B
Name: first_name, dtype: object

In [ ]:
#
t[t['first_name'].str.isdigit()]['first_name']

Series([], Name: first_name, dtype: object)

In [ ]:
# applying regex
# contains
# search john -> both case
# case= false means case sensitivity is false

t[t['first_name'].str.contains('john',case=False)]['first_name']

1            John Bradley (Florence Briggs Thayer)
41     William John Robert (Dorothy Ann Wonnacott)
45                                    William John
98                         John T (Ada Julia Bone)
112                                     David John
117                            William John Robert
160                                  John Hatfield
162                                    John Viktor
165                   Frank John William "Frankie"
168                                         John D
188                                           John
212                                     John Henry
226                                   William John
227                            John Hall ("Henry")
324                                 George John Jr
328                 Frank John (Emily Alice Brown)
401                                           John
418                                   William John
467                                John Montgomery
527                                           John
548                                     Frank John
549                                 John Morgan Jr
550                                John Borland Jr
563                                           John
572                          John Irwin ("Irving")
574                             Alfred George John
581        John Borland (Marian Longstreth Morris)
583                                      John Hugo
586                                    John Denzil
594                                     John Henry
613                                           John
624                               David John "Dai"
657                               John (Catherine)
694                                           John
698                                   John Borland
700          John Jacob (Madeleine Talmadge Force)
733                                   William John
760                                           John
765                          John C (Anna Andrews)
818                         John Fredrik Alexander
822                                    John George
825                                           John
848                                           John
864                                   John William
Name: first_name, dtype: object

In [ ]:
# find lastnames with start and end char vowel

t[t['lastname'].str.contains('^[aeiouAEIOU].+[aeiouAEIOU]$')]['first_name']

30                                     Manuel E
49                     Josef (Josefine Franchi)
207                               Nassef Cassem
210                                       Ahmed
353                                       Josef
493                                       Ramon
518    William A (Florence "Mary" Agnes Hughes)
784                                     William
840                               Ilmari Rudolf
Name: first_name, dtype: object

In [ ]:
# find lastnames with start and end char vowel

t[t['lastname'].str.contains('^[^aeiouAEIOU].+[^aeiouAEIOU]$')]['first_name']

0                                Owen Harris
1      John Bradley (Florence Briggs Thayer)
2                                      Laina
5                                      James
6                                  Timothy J
                       ...
884                                 Henry Jr
887                           Margaret Edith
888                 Catherine Helen "Carrie"
889                              Karl Howell
890                                  Patrick
Name: first_name, Length: 671, dtype: object

In [ ]:
# slicing
t['Name'].str[:4]

0      Brau
1      Cumi
2      Heik
3      Futr
4      Alle
       ...
886    Mont
887    Grah
888    John
889    Behr
890    Dool
Name: Name, Length: 891, dtype: object

In [ ]:
t['Name'].str[::-1]

0                                sirraH newO .rM ,dnuarB
1      )reyahT sggirB ecnerolF( yeldarB nhoJ .srM ,sg...
2                                 aniaL .ssiM ,nenikkieH
3           )leeP yaM yliL( htaeH seuqcaJ .srM ,ellertuF
4                               yrneH mailliW .rM ,nellA
                             ...
886                                sazouJ .veR ,alivtnoM
887                         htidE teragraM .ssiM ,maharG
888             "eirraC" neleH enirehtaC .ssiM ,notsnhoJ
889                                llewoH lraK .rM ,rheB
890                                  kcirtaP .rM ,yelooD
Name: Name, Length: 891, dtype: object