<a href="https://colab.research.google.com/github/Ghan539/Python4DataScientist/blob/main/pandas/Session16_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# pandas series - 1d array of data

In [3]:
import numpy as np
import pandas as pd

# Series from lists

country=['india','pakistan','usa','nepal','srilanka']
print(pd.Series(country))

0       india
1    pakistan
2         usa
3       nepal
4    srilanka
dtype: object

In [ ]:
# integers
runs=[13,24,56,78,100]
runs_series=pd.Series(runs)
print(runs_series)

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [ ]:
# .custom index
marks=[67,57,89,100]
subjects=['marks','english','science','hindi']
ss=pd.Series(subjects,index=marks,name='gshyam')
print(ss)

67       marks
57     english
89     science
100      hindi
Name: gshyam, dtype: object

In [ ]:
# Series from dict
marks={'marks':67,
       'english':57,
       'science':89,
       'hindi':100
       }
marks_series=pd.Series(marks,name='ghanshyam')
print(marks_series)

marks       67
english     57
science     89
hindi      100
Name: ghanshyam, dtype: int64

In [ ]:
# series attributes

marks_series.size

4

In [ ]:
# dype

marks_series.dtype

dtype('int64')

In [ ]:
# name

marks_series.name

'ghanshyam'

In [ ]:
# is_unique

print(marks_series.is_unique)

print(pd.Series([1,1,2,2,3,4,5,5]).is_unique)

True
False

In [ ]:
# index

marks_series.index

Index(['marks', 'english', 'science', 'hindi'], dtype='object')

In [ ]:
runs_series.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# values

marks_series.values

array([ 67,  57,  89, 100])

In [ ]:
# ṣeries using read_csv

with one column

In [ ]:
# with one col
type(pd.read_csv('/content/subs.csv'))

pandas.core.frame.DataFrame

In [9]:
sub=pd.read_csv('/content/subs.csv')
print(sub)

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [26]:
# kohli

kh=pd.read_csv('/content/kohli_ipl.csv',index_col='match_no')
print(kh)
print(kh.size)

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]
215

In [18]:
mov=pd.read_csv('/content/bollywood.csv')
print(mov)

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

series method

In [15]:
# series method
print(sub.head(10))

print(sub.tail(10))
print(kh.tail())

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44
5                  46
6                  33
7                  40
8                  44
9                  74
     Subscribers gained
355                 149
356                 156
357                 177
358                 210
359                 209
360                 231
361                 226
362                 155
363                 144
364                 172
          runs
match_no
211          0
212         20
213         73
214         25
215          7

In [20]:
# sample - one row randomly

mov.sample(5)

                movie              lead
134        Love Sonia  Abhishek Bharate
986        Sarkar Raj  Amitabh Bachchan
711            Barfi!     Ranbir Kapoor
1338  Dil Maange More     Shahid Kapoor
971       De Dana Dan      Akshay Kumar

In [23]:
# how much each actor moves done

ct=mov.value_counts()
print(ct)

movie                     lead
Andaaz                    Akshay Kumar       2
Tanu Weds Manu: Returns   Kangana Ranaut     2
Gabbar Is Back            Akshay Kumar       2
Noor (film)               Sunny Leone        1
No Smoking (2007 film)    John Abraham       1
                                            ..
Genius (2018 Hindi film)  Utkarsh Sharma     1
Gayab                     Tusshar Kapoor     1
Gauri: The Unborn         Mohan Azaad        1
Gattu                     Naresh Sharma      1
Global Baba               Pankaj Tripathi    1
Name: count, Length: 1497, dtype: int64

In [35]:
# highest score
kh.sort_values('runs',ascending=False).head(1).values[0]

array([113])

In [41]:
sor=kh.sort_values('match_no',ascending=True)
print(sor)
print(kh)

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]
          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [46]:
# sort_index____inplace----movies

kh.sort_values('runs',inplace=True)
print(kh)

          runs
match_no
8            0
87           0
93           0
91           0
206          0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

In [60]:
ss=mov.sort_values('movie')
print(ss)

ss1=mov.sort_values('lead')
print(ss1)

                         movie                lead
1022               1920 (film)    Rajniesh Duggall
287               1920: London       Sharman Joshi
725     1920: The Evil Returns         Vicky Ahuja
1040          1971 (2007 film)      Manoj Bajpayee
484       2 States (2014 film)        Arjun Kapoor
...                        ...                 ...
603              Zindagi 50-50         Veena Malik
780   Zindagi Na Milegi Dobara      Hrithik Roshan
672          Zindagi Tere Naam  Mithun Chakraborty
758                   Zokkomon     Darsheel Safary
941      Zor Lagaa Ke...Haiya!       Meghan Jadhav

[1500 rows x 2 columns]
                                 movie          lead
217                         Qaidi Band    Aadar Jain
553     Roar: Tigers of the Sundarbans  Aadil Chahal
205           Lipstick Under My Burkha  Aahana Kumra
974               Raat Gayi Baat Gayi?  Aamir Bashir
729    Talaash: The Answer Lies Within    Aamir Khan
...                                ...           ...
306                Dil Toh Deewana Hai   Zeenat Aman
257                    Sallu Ki Shaadi   Zeenat Aman
458                 Strings of Passion   Zeenat Aman
911           Dunno Y... Na Jaane Kyon   Zeenat Aman
1305  Taj Mahal: An Eternal Love Story   Zulfi Sayed

[1500 rows x 2 columns]

In [56]:
print(mov)

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [63]:
# count()

c=kh.count()
print()

In [64]:
sub.sum()

Subscribers gained    49510
dtype: int64

In [65]:
sub.product()

Subscribers gained    0
dtype: int64

In [71]:
# mean
sub.mean()

# median
print(kh.median())

# mode
print(mov.mode())

# standard deviation
print(sub.std())

# variance

print(kh.var())

runs    24.0
dtype: float64
                     movie          lead
0                   Andaaz  Akshay Kumar
1           Gabbar Is Back           NaN
2  Tanu Weds Manu: Returns           NaN
Subscribers gained    62.675023
dtype: float64
runs    688.002478
dtype: float64

In [74]:
# ṃax/min

print(sub.min())

print(sub.max())

Subscribers gained    33
dtype: int64
Subscribers gained    396
dtype: int64

In [76]:
# describe
kh.describe()
print(sub.describe())

       Subscribers gained
count          365.000000
mean           135.643836
std             62.675023
min             33.000000
25%             88.000000
50%            123.000000
75%            177.000000
max            396.000000