<a href="https://colab.research.google.com/github/Ghan539/Python4DataScientist/blob/main/pandas/session22_datetime_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
import pandas as pd

Timestamp Object
Time stamps reference particular moments in time (e.g., Oct 24th, 2022 at 7:00pm)

In [35]:
# creating a timestamp
pd.Timestamp('2023/1/5')

Timestamp('2023-01-05 00:00:00')

In [36]:
pd.Timestamp('2023-1-5')

Timestamp('2023-01-05 00:00:00')

In [37]:
pd.Timestamp('2023, 1, 5')

Timestamp('2023-01-05 00:00:00')

In [38]:
type(pd.Timestamp('2023/1/5'))

pandas._libs.tslibs.timestamps.Timestamp

In [39]:
# using text

pd.Timestamp('5th january 2026 12:22:32')

Timestamp('2026-01-05 12:22:32')

In [40]:
# time
pd.Timestamp('2020-11-21 , 9:12 AM')

Timestamp('2020-11-21 09:12:00')

In [41]:
# datetime
import datetime  as dt

dt.datetime(2023,1,5 ,9,21,43)

datetime.datetime(2023, 1, 5, 9, 21, 43)

In [42]:
x=pd.Timestamp(dt.datetime(2023,1,5 ,9,21,43))
x

Timestamp('2023-01-05 09:21:43')

In [43]:
x.year

2023

In [44]:
x.month

1

In [45]:
x.minute

21

In [46]:
# why separate objects to handle data and time when python already has datetime functionality?


syntax wise datetime is very convenient
But the performance takes a hit while working with huge data. List vs Numpy Array
The weaknesses of Python's datetime format inspired the NumPy team to add a set of native time series data type to NumPy.
The datetime64 dtype encodes dates as 64-bit integers, and thus allows arrays of dates to be represented very compactly.

In [47]:
import numpy as np
date=np.array('2019-07-21',dtype=np.datetime64)
date

array('2019-07-21', dtype='datetime64[D]')

In [48]:
date+np.arange(12)

array(['2019-07-21', '2019-07-22', '2019-07-23', '2019-07-24',
       '2019-07-25', '2019-07-26', '2019-07-27', '2019-07-28',
       '2019-07-29', '2019-07-30', '2019-07-31', '2019-08-01'],
      dtype='datetime64[D]')

In [49]:
# datetime64 is made by numpy for faster

Datetimeindex object

a collection of pandas timestamp

In [50]:
# from strings

pd.DatetimeIndex(['2023/1/1','2022/1/1','2021/1/1'])

DatetimeIndex(['2023-01-01', '2022-01-01', '2021-01-01'], dtype='datetime64[ns]', freq=None)

In [51]:
# using python datetime object

pd.DatetimeIndex([dt.datetime(2023,1,1),dt.datetime(2022,1,1),dt.datetime(2021,1,1)])

DatetimeIndex(['2023-01-01', '2022-01-01', '2021-01-01'], dtype='datetime64[ns]', freq=None)

In [57]:
# using pd.timestamps
dt_index=pd.DatetimeIndex([pd.Timestamp(2023,1,1),pd.Timestamp(2022,1,1),pd.Timestamp(2021,1,1)])

In [58]:
# using datetimeindex as series index__ index=dt_index
pd.Series([1,2,3],index = dt_index)

2023-01-01    1
2022-01-01    2
2021-01-01    3
dtype: int64

In [61]:
# generate daily dates in a given range
pd.date_range(start='2023/1/5',end='2023/4/5',freq='5D')

DatetimeIndex(['2023-01-05', '2023-01-10', '2023-01-15', '2023-01-20',
               '2023-01-25', '2023-01-30', '2023-02-04', '2023-02-09',
               '2023-02-14', '2023-02-19', '2023-02-24', '2023-03-01',
               '2023-03-06', '2023-03-11', '2023-03-16', '2023-03-21',
               '2023-03-26', '2023-03-31', '2023-04-05'],
              dtype='datetime64[ns]', freq='5D')

In [62]:
# alternate days in a given range
pd.date_range(start='2023/1/5',end='2023/2/28',freq='3D')

DatetimeIndex(['2023-01-05', '2023-01-08', '2023-01-11', '2023-01-14',
               '2023-01-17', '2023-01-20', '2023-01-23', '2023-01-26',
               '2023-01-29', '2023-02-01', '2023-02-04', '2023-02-07',
               '2023-02-10', '2023-02-13', '2023-02-16', '2023-02-19',
               '2023-02-22', '2023-02-25', '2023-02-28'],
              dtype='datetime64[ns]', freq='3D')

In [63]:
# B -> business days
pd.date_range(start='2023/1/5',end='2023/2/28',freq='B')

DatetimeIndex(['2023-01-05', '2023-01-06', '2023-01-09', '2023-01-10',
               '2023-01-11', '2023-01-12', '2023-01-13', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-23', '2023-01-24', '2023-01-25', '2023-01-26',
               '2023-01-27', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-06', '2023-02-07',
               '2023-02-08', '2023-02-09', '2023-02-10', '2023-02-13',
               '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
               '2023-02-20', '2023-02-21', '2023-02-22', '2023-02-23',
               '2023-02-24', '2023-02-27', '2023-02-28'],
              dtype='datetime64[ns]', freq='B')

In [67]:
# H -> Hourly data(factor)
pd.date_range(start='2023/1/5',end='2023/2/28',freq='6H')

/tmp/ipykernel_646/987353597.py:2: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range(start='2023/1/5',end='2023/2/28',freq='6H')

DatetimeIndex(['2023-01-05 00:00:00', '2023-01-05 06:00:00',
               '2023-01-05 12:00:00', '2023-01-05 18:00:00',
               '2023-01-06 00:00:00', '2023-01-06 06:00:00',
               '2023-01-06 12:00:00', '2023-01-06 18:00:00',
               '2023-01-07 00:00:00', '2023-01-07 06:00:00',
               ...
               '2023-02-25 18:00:00', '2023-02-26 00:00:00',
               '2023-02-26 06:00:00', '2023-02-26 12:00:00',
               '2023-02-26 18:00:00', '2023-02-27 00:00:00',
               '2023-02-27 06:00:00', '2023-02-27 12:00:00',
               '2023-02-27 18:00:00', '2023-02-28 00:00:00'],
              dtype='datetime64[ns]', length=217, freq='6h')

In [70]:
# W -> one week per day
pd.date_range(start='2023/1/1',end='2023/1/31',freq='D')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31'],
              dtype='datetime64[ns]', freq='D')

to_datetime function
converts an existing objects to pandas timestamp/datetimeindex object

In [72]:
# simple series example

s=pd.Series(['2023/1/1','2022/1/1','2021/1/1'])
s

0    2023/1/1
1    2022/1/1
2    2021/1/1
dtype: object

In [74]:
pd.to_datetime(s).dt.day_name()

0      Sunday
1    Saturday
2      Friday
dtype: object

In [78]:
# with errors
s = pd.Series(['2023/1/1','2022/2/21','2021/2/21'])
s

0     2023/1/1
1    2022/2/21
2    2021/2/21
dtype: object

In [79]:
pd.to_datetime(s,errors='coerce').dt.month_name()

0     January
1    February
2    February
dtype: object

In [ ]:
df=pd.read_csv()